### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Karldenforre** [ykob/tplh.net-2019#104]
Hi! Very amazing work! I am still a student but will learn more. I try to learn of this project, only for private purposes, not for online publishing. I tried to npm run build the package but I get blank page. Can you please tell me what I do wrong? Best wishes, Karl from Sweden

**Comment by ykob** [comment]
@Karldenforre 
What kind of terminal log would you see after running the command `npm run start` on your environment?
Or, the command is running without any errors?

**Comment by iiRedDev** [comment]
Hi, i am also learning three.js and I would like to learn more about your project but also, the concern.
![image](https://user-images.githubusercontent.com/73763294/161580270-16c043fb-7839-4fb7-a3f1-f014b03a0bba.png)

**Comment by iiRedDev** [comment]
[2022-04-04T15_36_00_616Z-debug-0.log](https://github.com/ykob/tplh.net-2019/files/8411087/2022-04-04T15_36_00_616Z-debug-0.log)

**Comment by ykob** [comment]
@iiRedDev 
Thanks for your comment.
It looks like the errors occur `node-sass` module, currently `node-sass` is [deprecated](https://github.com/sass/node-sass).
I have replaced `node-sass` to `sass` on [this PR](https://github.com/ykob/tplh.net-2019/pull/113), and merged it to `master`.
Could you run `yarn` command again?

**Comment by iiRedDev** [comment]
@ykob 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/73763294/161929970-86556920-785b-461b-a1ab-8abe0f47fc7d.png">
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/73763294/161931065-c3fd6933-e129-4792-b1f9-4a95bd7674e7.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/73763294/161931390-c2a8d8c5-d2ed-4f16-8b01-ad6640ef6d72.png">

Hello, thank you for your answer.
I'm not sure if it's a good idea to use the same software as the one you're using now, but I'm not sure if it's a good idea to use the same software as the one you're using now, so I'm not sure if it's a good idea to use the same software as the one you're using now.

**Comment by iiRedDev** [comment]
hi, if you have a solution I'm interested ^^
